<a href="https://colab.research.google.com/github/KMR-86/All-My-random-codes/blob/master/felseinteins_prunning_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
from scipy import linalg

Q=np.array([[-1.916,0.541,0.787,0.588],[0.148,-1.069,0.415,0.506],[0.286,0.170,-0.591,0.135],[0.525,0.236,0.594,-1.355]])
print(Q)



[[-1.916  0.541  0.787  0.588]
 [ 0.148 -1.069  0.415  0.506]
 [ 0.286  0.17  -0.591  0.135]
 [ 0.525  0.236  0.594 -1.355]]


This code will give 0.0 for all the rows if the array's format is like a continuous time markov chain

In [19]:
def test_if_ctmc(Q):
  for i in range(0,Q.shape[0]):
    if np.sum(Q[i])!=0.0:
      print(i+" no row has a problem")
      return -1;
  
  print("ok\n")

test_if_ctmc(Q)

ok



In [20]:
def get_transition_probability_p(Q,t,i,j):
  return linalg.expm((Q*t))[i][j]

print(get_transition_probability_p(Q,100,1,1))

0.18794332469009922


In [21]:
Cl=(0,0,1,0)
Cr=(0,0,0,1)
Vl=0.15
Vr=0.15
ans=[]
for i in range(0,Q.shape[0]):
  suml=0
  sumr=0
  for j in range(0,Q.shape[1]):
    suml=suml+get_transition_probability_p(Q,Vl,i,j)*Cl[j]
    sumr=sumr+get_transition_probability_p(Q,Vr,i,j)*Cr[j]
  
  ans.append(suml*sumr)

print(ans)


[0.007548388682161947, 0.003839147281928645, 0.018382948223364313, 0.06742248848200644]


In [22]:
def calculate_ML_from_child(left_child,right_child,left_length,right_length,Q):
  ans=[]
  for i in range(0,Q.shape[0]):
    sum_l=0
    sum_r=0
    for j in range(0,Q.shape[1]):
      sum_l=sum_l+get_transition_probability_p(Q,left_length,i,j)*left_child[j]
      sum_r=sum_r+get_transition_probability_p(Q,right_length,i,j)*right_child[j]

    ans.append(sum_l*sum_r)
  
  return ans

Cl=(0,0,1,0)
Cr=(0,0,0,1)
print(calculate_ML_from_child(Cl,Cr,0.15,0.15,Q))

    

[0.007548388682161947, 0.003839147281928645, 0.018382948223364313, 0.06742248848200644]
