<a href="https://colab.research.google.com/github/KMR-86/All-My-random-codes/blob/master/felseinteins_prunning_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from scipy import linalg

Q=np.array([[-1.916,0.541,0.787,0.588],[0.148,-1.069,0.415,0.506],[0.286,0.170,-0.591,0.135],[0.525,0.236,0.594,-1.355]])
print(Q)



[[-1.916  0.541  0.787  0.588]
 [ 0.148 -1.069  0.415  0.506]
 [ 0.286  0.17  -0.591  0.135]
 [ 0.525  0.236  0.594 -1.355]]


This code will give 0.0 for all the rows if the array's format is like a continuous time markov chain

In [12]:
def test_if_ctmc(Q):
  for i in range(0,Q.shape[0]):
    if np.sum(Q[i])!=0.0:
      print(i+" no row has a problem")
      return -1;
  
  print("ok\n")

test_if_ctmc(Q)

ok



In [14]:
def get_transition_probability_p(t):
  return linalg.expm((Q*t))

print(get_transition_probability_p(100))

[[0.13755573 0.18794332 0.49527966 0.17922129]
 [0.13755573 0.18794332 0.49527966 0.17922129]
 [0.13755573 0.18794332 0.49527966 0.17922129]
 [0.13755573 0.18794332 0.49527966 0.17922129]]
